# Generated by Django 5.0.6 on 2024-07-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="watchlist_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
