# Generated by Django 5.0.6 on 2024-07-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_remove_movies_director_remove_movies_genre_and_more"),
        ("watchlist", "0003_remove_watchlist_movie_watchlist_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="movie",
            field=models.ManyToManyField(blank=True, null=True, to="movies.movies"),
        ),
    ]
