# Generated by Django 5.0.6 on 2024-07-11 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0014_alter_movie_options"),
        ("watchlist", "0005_remove_watchlist_movie_watchlist_movie"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="watchlist",
            constraint=models.UniqueConstraint(
                fields=("user", "movie"), name="unique_watchlist_movie"
            ),
        ),
    ]
