# Generated by Django 5.0.6 on 2024-06-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
