# Generated by Django 5.0.6 on 2024-07-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movies_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="movieid",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
