# Generated by Django 5.0.6 on 2024-07-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_movies_movieid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="movies",
            name="directors",
            field=models.ManyToManyField(
                related_name="directed_movies", to="movies.director"
            ),
        ),
        migrations.AddField(
            model_name="movies",
            name="genres",
            field=models.ManyToManyField(related_name="movies", to="movies.genre"),
        ),
        migrations.AddField(
            model_name="movies",
            name="tags",
            field=models.ManyToManyField(related_name="tagged_movies", to="movies.tag"),
        ),
    ]
