# Generated by Django 5.0.6 on 2024-07-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_director_genre_tag_movies_directors_movies_genres_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movies",
            name="director",
        ),
        migrations.RemoveField(
            model_name="movies",
            name="genre",
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
