# Generated by Django 5.0.6 on 2024-07-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_remove_movies_director_remove_movies_genre_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movies",
            options={"verbose_name_plural": "Movies"},
        ),
    ]
