# Generated by Django 5.0.6 on 2024-07-11 11:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deleted_movies", "0005_rename_deletedmovies_deletedmovie"),
        ("movies", "0006_alter_movies_options"),
        ("ratings", "0004_alter_ratings_movie"),
        ("reviews", "0003_alter_reviews_options"),
        ("user_movies", "0003_alter_usermovies_options"),
        ("watchlist", "0005_remove_watchlist_movie_watchlist_movie"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Movies",
            new_name="Movie",
        ),
    ]
