# Generated by Django 5.0.6 on 2024-07-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_rename_movies_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
