# Generated by Django 5.0.6 on 2024-07-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_alter_director_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="releaseyear",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
