# Generated by Django 5.0.6 on 2024-07-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_alter_movie_runtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="boxoffice",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
