# Generated by Django 5.0.6 on 2024-07-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0013_alter_movie_budget"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["-releaseyear"], "verbose_name_plural": "Movies"},
        ),
    ]
