# Generated by Django 5.0.6 on 2024-07-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0014_alter_movie_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                related_name="genre_movies", to="movies.genre"
            ),
        ),
    ]
