# Generated by Django 5.0.6 on 2024-07-10 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deleted_movies", "0002_alter_deletedmovies_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deletedmovies",
            options={"verbose_name": "Deleted movies"},
        ),
    ]
