# Generated by Django 5.0.6 on 2024-07-06 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_movies_movieid"),
        ("ratings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratings",
            name="rating",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="ratings",
            name="rating_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name="ratings",
            constraint=models.CheckConstraint(
                check=models.Q(("rating__gte", 1.0), ("rating__lte", 10.0)),
                name="rating_range",
            ),
        ),
    ]
