# Generated by Django 5.0.6 on 2024-07-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_alter_ratings_rating_alter_ratings_rating_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ratings",
            options={"verbose_name_plural": "Ratings"},
        ),
    ]
