# Generated by Django 5.0.6 on 2024-07-11 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_alter_movies_options"),
        ("ratings", "0003_alter_ratings_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratings",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="movies.movies",
            ),
        ),
    ]
