# Generated by Django 5.0.6 on 2024-07-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermovies",
            name="user_movie_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
