# Generated by Django 5.0.6 on 2024-07-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_movies", "0002_alter_usermovies_user_movie_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermovies",
            options={"verbose_name_plural": "User Movies"},
        ),
    ]
