GENRE_CHOICES = {
    "AC": "Action",
    "AD": "Adventure",
    "AN": "Animation",
    "CO": "Comedy",
    "CR": "Crime",
    "DO": "Documentary",
    "DR": "Drama",
    "FA": "Family",
    "FN": "Fantasy",
    "HI": "History",
    "HO": "Horror",
    "MU": "Music",
    "MY": "Mystery",
    "RO": "Romance",
    "SF": "Science Fiction",
    "TH": "Thriller",
    "WA": "War",
    "WE": "Western",
    "MS": "Musical",
    "BI": "Biography",
}
