# Generated by Django 5.0.6 on 2024-07-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_reviews_review_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviews",
            options={"verbose_name_plural": "Reviews"},
        ),
    ]
