# Generated by Django 5.0.6 on 2024-07-11 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0014_alter_movie_options"),
        ("reviews", "0004_rename_reviews_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user", "movie"), name="unique_review"
            ),
        ),
    ]
